services:
#  mariadb:
#    image: 'mariadb:latest'
#    environment:
#      - 'MARIADB_DATABASE=mydatabase'
#      - 'MARIADB_PASSWORD=secret'
#      - 'MARIADB_ROOT_PASSWORD=verysecret'
#      - 'MARIADB_USER=myuser'
#    ports:
#      - '3307:3307'
  mysql:
    container_name: 'guide-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_ROOT_PASSWORD=verysecret' # root
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_USER=myuser'
      - 'MYSQL_PASSWORD=secret'
    ports:
      - '3306:3306'
#  oracle:
#    image: 'gvenzl/oracle-free:latest'
#    environment:
#      - 'ORACLE_PASSWORD=secret'
#      - 'APP_USER=tester'
#      - 'APP_USER_PASSWORD=tester1234!'
#    ports:
#      - '1521:1521'
#  postgres:
#    image: 'postgres:latest'
#    environment:
#      - 'POSTGRES_DB=mydatabase'
#      - 'POSTGRES_PASSWORD=secret'
#      - 'POSTGRES_USER=myuser'
#    ports:
#      - '5432:5432'
#  sqlserver:
#    image: 'mcr.microsoft.com/mssql/server:latest'
#    environment:
#      - 'ACCEPT_EULA=yes'
#      - 'MSSQL_PID=express'
#      - 'MSSQL_SA_PASSWORD=verYs3cret'
#    ports:
#      - '1433:1433'
